export const GET_POSITIONS_FETCHING = 'GET_POSITIONS_FETCHING';
export const GET_POSITIONS_FULFILLED = 'GET_POSITIONS_FULFILLED';
export const GET_POSITIONS_REJECTED = 'GET_POSITIONS_REJECTED';
export const ERROR_TO_DEFAULT = 'ERROR_TO_DEFAULT';
