export const GET_INTERVIEWS_FETCHING = 'GET_INTERVIEWS_FETCHING';
export const GET_INTERVIEWS_FULFILLED = 'GET_INTERVIEWS_FULFILLED';
export const GET_INTERVIEWS_REJECTED = 'GET_INTERVIEWS_REJECTED';
export const ERROR_TO_DEFAULT = 'ERROR_TO_DEFAULT';
