export const GET_INTERVIEWS_FETCHING = 'GET_INTERVIEWS_FETCHING';
export const GET_INTERVIEWS_FULFILLED = 'GET_INTERVIEWS_FULFILLED';
export const GET_INTERVIEWS_REJECTED = 'GET_INTERVIEWS_REJECTED';
export const DELETE_INTERVIEW_FETCHING = 'DELETE_INTERVIEWS_FETCHING';
export const DELETE_INTERVIEW_FULFILLED = 'ELETE_INTERVIEW_FULFILLED';
export const DELETE_INTERVIEW_REJECTED = 'DELETE_INTERVIEW_REJECTED';
export const ERROR_TO_DEFAULT = 'ERROR_TO_DEFAULT';
