export const GET_CLIENTS_FETCHING = 'GET_CLIENTS_FETCHING';
export const GET_CLIENTS_FULFILLED = 'GET_CLIENTS_FULFILLED';
export const GET_CLIENTS_REJECTED = 'GET_CLIENTS_REJECTED';

export const GET_ONE_CLIENT_FETCHING = 'GET_ONE_CLIENT_FETCHING';
export const GET_ONE_CLIENT_FULFILLED = 'GET_ONE_CLIENT_FULFILLED';
export const GET_ONE_CLIENT_REJECTED = 'GET_ONE_CLIENT_REJECTED';

export const ADD_CLIENT_FETCHING = 'ADD_CLIENT_FETCHING';
export const ADD_CLIENT_FULFILLED = 'ADD_CLIENT_FULFILLED';
export const ADD_CLIENT_REJECTED = 'ADD_CLIENT_REJECTED';

export const UPDATE_CLIENT_FETCHING = 'UPDATE_CLIENT_FETCHING';
export const UPDATE_CLIENT_FULFILLED = 'UPDATE_CLIENT_FULFILLED';
export const UPDATE_CLIENT_REJECTED = 'UPDATE_CLIENT_REJECTED';

export const DELETE_CLIENT_FETCHING = 'DELETE_CLIENT_FETCHING';
export const DELETE_CLIENT_FULFILLED = 'DELETE_CLIENT_FULFILLED';
export const DELETE_CLIENT_REJECTED = 'DELETE_CLIENT_REJECTED';

export const ERROR_TO_DEFAULT = 'ERROR_TO_DEFAULT';
export const SELECTED_TO_DEFAULT = 'SELECTED_TO_DEFAULT';
